FROM eclipse-temurin:19-jdk

LABEL author="Leafd" \
      maintainer="hi@leafd.tech" \
      org.opencontainers.image.source="https://github.com/LeafdTK/Images" \
      org.opencontainers.image.licenses="MIT"

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    curl \
    ca-certificates \
    openssl \
    git \
    tar \
    sqlite3 \
    fontconfig \
    libfreetype6 \
    libstdc++6 \
    lsof \
    build-essential \
    tzdata \
    iproute2 \
    locales && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -m -d /home/container container && \
    locale-gen en_US.UTF-8

ENV LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US.UTF-8

USER container
ENV USER=container \
    HOME=/home/container
WORKDIR /home/container
